fix timers for PP and add tts + a little fix Marro and add tts
Zidras/DBM-Icecrown pull request #20
Opened 2021-07-26 00:37 UTC by Nispodzianka

2021-07-26 01:04 UTC, Nispodzianka commented on DBM-Icecrown/TheLowerSpire/LordMarrowgar.lua
> -local timerWhirlwindCD		= mod:NewCDTimer(30, 69076, nil, nil, nil, 2, nil, DBM_CORE_L.MYTHIC_ICON, nil, 1) -- Edited
I didn't know you changed DAMAGE_ICON > MYTHIC_ICON
I only deleted "nil, 1" because I don't need to hear it due to the added tts call

2021-07-26 01:07 UTC, Nispodzianka commented on DBM-Icecrown/TheLowerSpire/LordMarrowgar.lua
> -		preWarnWhirlwind:Schedule(80) -- Edited
I move this to mod:SPELL_AURA_REMOVED (line 72)
it worked badly in your version

2021-07-26 01:17 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|Hunter") -- Phase 3 ability
I just see that "Tank|Healer|**Hunter**" is not working and must be used "Tank|Healer|**RemoveEnrage**"

2021-07-26 01:37 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
DBM doesn't know what Hunter means, so I used RemoveEnrage

2021-07-26 01:53 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +			self:ScheduleMethod(26, "NextPhase")
in HC mode, I want the info about the new phase to appear just before the boss attacks the tank, otherwise if the info about the phase change is too late, the timers will not match
this can also be done to start a new phase as soon as the boss starts casting the spell and only set the timer when the new phase starts

2021-07-26 08:02 UTC, Zidras commented
General sounds like gtfo are not needed. Use the appropriate VoicePack entry if you wish to propose a change in the code

2021-07-26 09:05 UTC, Nispodzianka commented
> General sounds like gtfo are not needed. Use the appropriate VoicePack entry if you wish to propose a change in the code

There is no VoicePack in your DBM version that I can set up. I could use the additional GTFO addon but the goal I have in tweaking DBM is that others do not have to search the internet for additional addons to help with Raids. After watching your stream, I know that you do not have any voice notification about standing on fire - on Lordaeron, if you are on fire, you die, so I consider it very important on this boss.

2021-07-26 09:10 UTC, Zidras commented
> > General sounds like gtfo are not needed. Use the appropriate VoicePack entry if you wish to propose a change in the code
> 
> There is no VoicePack in your DBM version that I can set up. I could use the additional GTFO addon but the goal I have in tweaking DBM is that others do not have to search the internet for additional addons to help with Raids. After watching your stream, I know that you do not have any voice notification about standing on fire - on Lordaeron, if you are on fire, you die, so I consider it very important on this boss.

https://user-images.githubusercontent.com/10605951/120121681-bf17d080-c19c-11eb-9c5c-77e131e92c14.png

2021-07-26 18:27 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
>  local warnTearGas					= mod:NewSpellAnnounce(71617, 2)		-- Phase transition normal
Reverting this. Even though it's never fired on warmane, I want to keep it in for 2 reasons:
- Other servers that have proper scripts;
- If Warmane ever fixes it.

2021-07-26 18:30 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
These flags are coded in Core.lua (search for the specFlags table).
Even though RemoveEnrage also includes Rogues, I don't mind the addition.

2021-07-26 18:35 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
Also on the topic of flags, all Tanks are melee, so the extra flag you added for Tank is not necessary

2021-07-26 18:37 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
Healers are also all Ranged

2021-07-26 18:52 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local ttsSlimePuddle 				= mod:NewSound(70341)
Bringing this back for the same reason above

2021-07-26 18:59 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local ttsNextPhaseSoon 				= mod:NewSound("TTS NextPhaseSoon")
Localize this, or present a localized alternative

2021-07-26 19:10 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +			self:ScheduleMethod(26, "NextPhase")
This is not the way to do it. Phasing not only handles timers but also fires a Stage Callback that signal 3rd party addons of phase change

2021-07-26 21:58 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +			self:ScheduleMethod(26, "NextPhase")
in accordance with https://wowwiki-archive.fandom.com/wiki/Professor_Putricide
3.1 Phase 1: 100% to 80%
3.2 Phase 2: 80% to 35%
3.3 Phase 3: 35% to 0%
so technically speaking, the new Norm phase should start when Tear Gas is cast, not when the debuff disappears, and on HC the next phase starts with summoning 2 oozes. Someone writing DBM timers did it differently but it doesn't change much because at least Warmane timers are counted in a specific way when changing phase and they do not stop even for a moment and what we show or do not show with timers in DBM will not change it.

2021-07-26 22:05 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
unfortunately I don't know how to add Hunter instead of RemoveEnrage
As for Tank|Melee, this is the record used in the old DBM version, now I will know that it is not necessary

2021-07-26 23:02 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +			self:ScheduleMethod(26, "NextPhase")
I have to disagree with you on that. If I take LK as an example, every phasing has a transition (remorseless winter), and every phase BEGINS at the end of the cast, not at the beginning; you could argue phase 1 should stop at cast start, but you'd still end up with transition time unaccounted for. So why bother?
I don't mind reinventing the wheel, if the new wheel works better... here you are just reducing the scheduleTimer to make it fire timers earlier, which is very lazy approach (and wrong)

2021-07-26 23:03 UTC, Zidras commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +local warnMutatedPlague				= mod:NewStackAnnounce(72451, 3, nil, "Tank|Healer|RemoveEnrage") -- Phase 3 ability
no need to add hunter. just keep it like you proposed, it's fine

2021-07-26 23:10 UTC, Zidras requested changes
- Caching GetTime() for every var is not a very elegant approach. DBM has built-in functions to add/update timers. This needs some work.
- Don't forget to localize your additions. I'm not a fan of Next Phase soon tts, but I can see it's usefulness. This could be an interesting addition to the upcoming VoicePack, so until then you either localize this for every language, or simply remove it and propose the change later
- Don't remove code just because it's commented out, please. Nor remove code because it doesn't work on Warmane - I have reverted your changes on this front, but keep this in mind in future PRs :)

2021-08-06 14:50 UTC, Nispodzianka commented on DBM-Icecrown/ThePlagueworks/Putricide.lua
> +			if (GetTime()-PuddleTime) > 35 then
0:00 start fight
0:10 cast Puddle "PuddleTime = GetTime()"
0:41 Tear Gas (start cast and boss runs to the table)
0:45 (the boss is still running, he should cast Puddle but cant because of Tear Gas)
0:47 Create Concoction start cast
therefore I check if the boss had a chance to cast Puddle, which means the time between Create Concoction and the last cast Puddle is greater than 35s
not tested yet

2021-08-15 15:38 UTC, Zidras approved these changes

2021-08-15 15:58 UTC, merged