ToC Update
Zidras/DBM-Icecrown pull request #3
Opened 2021-07-01 18:34 UTC by Ayaro1

ToC 10/25 NM/HC boss timer fixes and additions for Warmane (Icecrown)

2021-07-01 20:44 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +
Why is there a need to hardcode this? Timers for second are being set on CHAT_MSG_RAID_BOSS_EMOTE

2021-07-01 20:44 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +	timerEmergeTwo:Schedule(225)
Same here

2021-07-01 20:46 UTC, Ayaro1 commented on DBM-Coliseum/Anub'arak.lua
> +
The original timers aren't picked up consistently after the first Submerge.
You can see it happen in the video i sent you from my balance druid pov

2021-07-01 20:47 UTC, Ayaro1 commented on DBM-Coliseum/Anub'arak.lua
> +	timerEmergeTwo:Schedule(225)
The original timers aren't picked up consistently after the first Submerge.
You can see it happen in the video i sent you from my balance druid pov

2021-07-01 20:53 UTC, Zidras commented on DBM-Icecrown/FrostwingHalls/Sindragosa.lua
> +local berserkTimerLordaeron		= mod:NewTimer(390, "Berserk Timer Lordaeron", nil, false)
I personally do not agree in adding both timers to the boss options. I think caching the server and then check it on module load whether is shows or not based on cache might be a cleaner approach

2021-07-01 20:54 UTC, Ayaro1 commented on DBM-Icecrown/FrostwingHalls/Sindragosa.lua
> +local berserkTimerLordaeron		= mod:NewTimer(390, "Berserk Timer Lordaeron", nil, false)
Fair point. It's disabled by default tho.

2021-07-01 20:54 UTC, Zidras commented on DBM-Icecrown/TheCrimsonHall/Lanathel.lua
> +local berserkTimerLordaeron			= mod:NewTimer(300, "Berserk Timer Lordaeron", nil, false)
Same comment here. Not a fan of this approach

2021-07-01 20:55 UTC, Ayaro1 commented on DBM-Icecrown/TheCrimsonHall/Lanathel.lua
> +local berserkTimerLordaeron			= mod:NewTimer(300, "Berserk Timer Lordaeron", nil, false)
Fair point. Like the above, it's disabled by default.

2021-07-01 20:58 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +mod:AddBoolOption("RemoveDruidBuff", true, not mod:IsTank())
I hate this feature. I understand its purpose, but no way I'm leaving this anything else than false for defaultOption, especially since default DBM behaviour is using global namespace for profile (so it applies to all characters)

2021-07-01 21:00 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +mod:AddBoolOption("RemoveDruidBuff", true, not mod:IsTank())
Never realized it saves settings globally now instead of per char. Not a good idea than no.

2021-07-01 21:01 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +mod:AddBoolOption("RemoveDruidBuff", true, not mod:IsTank())
Also, args are wrong. 
```
mod:AddBoolOption("RemoveDruidBuff", false, "misc")
```

2021-07-01 21:03 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +end
Move this up. Before the "normal" code. Maybe after mod:EqW()

2021-07-01 21:05 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +end
Done

2021-07-01 21:06 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/LordMarrowgar.lua
> +local timerWhirlwindCD		= mod:NewCDTimer(90, 69076, nil, nil, nil, 2, nil, DBM_CORE_MYTHIC_ICON, nil, 1) -- Edited
This needs to be re-evaluated, as there is way too much variance. Either the variance is too high due to server scripting, or detect if there's a reliable way to time 2nd bonestorm.

2021-07-02 13:13 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +mod:AddBoolOption("RemoveDruidBuff", true, not mod:IsTank())
Should be good now

2021-07-02 22:34 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +	CancelUnitBuff("player", (GetSpellInfo(48470)))		-- Gift of the Wild Rank 4
All ranks not needed. This is removing by name

2021-07-02 23:04 UTC, Zidras commented on DBM-Coliseum/NorthrendBeasts.lua
> +		timerNextCrashTwo:Schedule(52)
Shouldn't this be covered by:
```
function mod:UNIT_SPELLCAST_SUCCEEDED(uId, spellName)
	if spellName == GetSpellInfo(66683) then
		timerNextCrash:Cancel()
		timerNextCrash:Start(49)
	end
end
```
If there's work to be done, it should be there. 
Having two timers running simultaneously for not immediate events is not efficient

2021-07-03 13:50 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +
This is perhaps a cleaner workaround to Warmane's missing emerge event:
```
-- Warmane workaround, since emerge boss emote is not being fired
function mod:EmergeFix()
	Burrowed = false
	timerEmerge:Cancel()
	timerAdds:Start(5)
	warnAdds:Schedule(5)
	self:ScheduleMethod(5, "Adds")
	warnEmerge:Show()
	warnSubmergeSoon:Schedule(65)
	specWarnSubmergeSoon:Schedule(65)
	timerSubmerge:Start()
	if mod:IsDifficulty("heroic10") or mod:IsDifficulty("heroic25") then
		timerShadowStrike:Stop()
		preWarnShadowStrike:Cancel()
		self:UnscheduleMethod("ShadowStrike")
		self:ScheduleMethod(5.0, "ShadowStrike")
	end
end
```
```
function mod:CHAT_MSG_RAID_BOSS_EMOTE(msg)
	if msg and msg:find(L.Burrow) then
		Burrowed = true
		timerAdds:Cancel()
		warnAdds:Cancel()
		warnSubmerge:Show()
		warnEmergeSoon:Schedule(55)
		timerEmerge:Start()
		timerFreezingSlash:Stop()
		timerShadowStrike:Stop()
		preWarnShadowStrike:Cancel()
		self:UnscheduleMethod("ShadowStrike")
		self:ScheduleMethod(65, "EmergeFix")	-- Warmane workaround, since emerge boss emote is not being fired
	elseif msg and msg:find(L.Emerge) then
		self:UnscheduleMethod("EmergeFix")		-- Warmane workaround: failsafe if script gets fixed eventually
		Burrowed = false
		timerEmerge:Cancel()
		timerAdds:Start(5)
		warnAdds:Schedule(5)
		self:ScheduleMethod(5, "Adds")
		warnEmerge:Show()
		warnSubmergeSoon:Schedule(65)
		specWarnSubmergeSoon:Schedule(65)
		timerSubmerge:Start()
		if mod:IsDifficulty("heroic10") or mod:IsDifficulty("heroic25") then
			timerShadowStrike:Stop()
			preWarnShadowStrike:Cancel()
			self:UnscheduleMethod("ShadowStrike")
			self:ScheduleMethod(5.0, "ShadowStrike")
		end
	end
end
```
65 seconds timer on the schedule might need some ms adjustement.

2021-07-03 14:01 UTC, Zidras commented on DBM-Coliseum/Jaraxxus.lua
> +local timerPortalTwo			= mod:NewTimer(120, "2nd Nether Portal")
Again, this is not the way :)
If for some reason the spell_cast_success is not starting TimerPortalCD, then we need to look into that first, before hardcoding yet another (2 min!!) timer

2021-07-03 14:03 UTC, Zidras commented on DBM-Coliseum/Jaraxxus.lua
> +local timerPortalTwo			= mod:NewTimer(120, "2nd Nether Portal")
Looking at the footage, it seems like there's a RAID_BOSS_EMOTE for this too, which we can use if there's no CLEU event

2021-07-03 16:15 UTC, Zidras commented on DBM-Icecrown/FrostwingHalls/Sindragosa.lua
> +local berserkTimerLordaeron		= mod:NewTimer(390, "Berserk Timer Lordaeron", nil, false)
For Lord enrages, let's do this instead:
```
local berserkTimer				= select(3, DBM:GetMyPlayerInfo()) == "Lordaeron" and mod:NewBerserkTimer(390) or mod:NewBerserkTimer(600)
```

This logic applies to all different lord enrage timers

2021-07-03 16:18 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +	timerEmergeTwo:Schedule(225)
See above

2021-07-03 16:20 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/LordMarrowgar.lua
> +local timerWhirlwindCD		= mod:NewCDTimer(90, 69076, nil, nil, nil, 2, nil, DBM_CORE_MYTHIC_ICON, nil, 1) -- Edited
I have pushed a different way to handle this mechanic, and for the different VOD sources I checked, it looks accurate with any variation

2021-07-03 17:12 UTC, Ayaro1 commented on DBM-Coliseum/Anub'arak.lua
> +
65 second timer is 100% accurate. Has been for months and months

2021-07-03 17:15 UTC, Ayaro1 commented on DBM-Icecrown/FrostwingHalls/Sindragosa.lua
> +local berserkTimerLordaeron		= mod:NewTimer(390, "Berserk Timer Lordaeron", nil, false)
Done

2021-07-03 17:17 UTC, Ayaro1 commented on DBM-Coliseum/Anub'arak.lua
> +
Changes done

2021-07-03 17:19 UTC, Ayaro1 commented on DBM-Coliseum/Anub'arak.lua
> +	timerEmergeTwo:Schedule(225)
They're commented out. That enough or pref removal?

2021-07-03 17:21 UTC, Ayaro1 commented on DBM-Icecrown/TheCrimsonHall/Lanathel.lua
> +local berserkTimerLordaeron			= mod:NewTimer(300, "Berserk Timer Lordaeron", nil, false)
Updated the same way as the Sindy enrage timer.

2021-07-03 17:23 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +
I meant the schedule timer that I added to the enragefix :) the timer is totally correct. but the event fires like 100ms before the actual 65s timer. Just wanted to leave it for posterity

2021-07-03 17:25 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +	timerEmergeTwo:Schedule(225)
I would prefer removal. And also remove those warningsTwo and specWarningsTwo. 
EnrageFix function is reusing all the warnings.

2021-07-03 17:29 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +	CancelUnitBuff("player", (GetSpellInfo(48470)))		-- Gift of the Wild Rank 4
Cleanup done

2021-07-03 17:41 UTC, Zidras requested changes
Made some comments where changes still needed

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +
Delete

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +	-- timerEmergeOne:Schedule(80)
Delete

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Anub'arak.lua
> +	-- timerEmergeTwo:Schedule(225)
Delete

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Twins.lua
> +--local timerRoleplay					= mod:NewTimer(115, "TimerRoleplay", "Interface\\Icons\\Spell_Holy_BorrowedTime")
I haven't done ToC in a while. If you confirm we have to speak with the NPC to start the roleplay, you can delete this.

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Twins.lua
> +end]]--
Delete if above checks out.

2021-07-03 17:41 UTC, Zidras commented on DBM-Icecrown/FrostwingHalls/Sindragosa.lua
> +	berserkTimerLordaeron:Start()
Delete

2021-07-03 17:41 UTC, Zidras commented on DBM-Icecrown/TheCrimsonHall/Lanathel.lua
> +	berserkTimerLordaeron:Start(-delay)
Delete

2021-07-03 17:41 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +	CancelUnitBuff("player", (GetSpellInfo(48470)))		-- Gift of the Wild Rank 4
Purge ranks.

2021-07-03 17:41 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +		timerAdds:Start()
Why change this?

2021-07-03 17:41 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/LordMarrowgar.lua
> +local timerWhirlwindCD		= mod:NewCDTimer(90, 69076, nil, nil, nil, 2, nil, DBM_CORE_MYTHIC_ICON, nil, 1) -- Edited
So you can revert the changes of marrowgar entirely :)

2021-07-03 17:41 UTC, Zidras commented on DBM-Coliseum/Jaraxxus.lua
> +	timerPortalTwo:Schedule(22)
Same as above. Workaround might be possible (will have to confirm with transcriptor logs)

2021-07-03 17:43 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +		timerAdds:Start()
That's the original code that differentiates normal mode and heroic mode
The code used now forces the boss mode to use heroic timers for adds on normal mode

2021-07-03 17:44 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +		timerAdds:Start()
updated code also checks for heroic, here:
```
	if self:IsDifficulty("heroic10", "heroic25") then
	```

2021-07-03 17:46 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +		timerAdds:Start()
only change here necessary are the timers themselves, after the else. Code logic in that function is solid

2021-07-03 17:46 UTC, Ayaro1 commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +		timerAdds:Start()
But it still used the 45 sec timer for normal instead of the 60 sec one cause that's what i forced it to do in the past. I see i updated that part the wrong way

2021-07-04 09:23 UTC, Zidras commented on DBM-Icecrown/TheLowerSpire/Deathwhisper.lua
> +local timerAdds						= mod:NewTimer(60, "TimerAdds", 61131, nil, nil, 1, DBM_CORE_TANK_ICON..DBM_CORE_DAMAGE_ICON)
This change is unnecessary. All timers are hardcoded in the function anyway.

2021-07-04 09:31 UTC, merged